import "./globals.css";


export const metadata = {
  title: "Header",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
   children

  );
}
