import "../styles/globals.css";
import "../styles/responsive.css";


export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
   <html lang="en">
      <body>
        {children}
      </body>
    </html>

  );
}
